drop table if exists item CASCADE;
create table item
(
    id        bigint generated by default as identity,
    item_name varchar(100),
    price     integer,
    quantity  integer,
    primary key (id)
)